name: Pull Request Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: ""
          python-version: "3.12"

      - name: Run primal-page validate
        run: uvx primal-page validate all-schemes ./primerschemes
